language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - nvm install 4
  - nvm use 4
  - npm install -g dynalite
script:
  - flake8 --ignore=E501 --exclude=node_modules
  - dynalite --port 4567 &
  - mkdir -p dumps && cp -a test/testTable dumps
  - python ddb-backup.py -v --log info -m restore -r local -s testTable -d testRestoredTable --host localhost --port 4567 --accessKey a --secretKey a
  - python ddb-backup.py -v --log info -m backup -r local -s testRestoredTable --host localhost --port 4567 --accessKey a --secretKey a
  - python test/test.py
matrix:
  fast_finish: true